// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import ()

type Auth struct {
	ID     int64  `json:"id"`
	ApiKey string `json:"api_key"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

type UserDatum struct {
	UserID int64  `json:"user_id"`
	School string `json:"school"`
}

type UserProfile struct {
	UserID    int64  `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Phone     string `json:"phone"`
	Address   string `json:"address"`
	City      string `json:"city"`
}
