// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountApiKey(ctx context.Context, apiKey string) (int64, error)
	GetProfile(ctx context.Context, username string) (GetProfileRow, error)
	GetProfiles(ctx context.Context) ([]GetProfilesRow, error)
}

var _ Querier = (*Queries)(nil)
