version: '2.2'

services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: ..
    command: /app/school-auth
    depends_on:
      - mysql
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    env_file:
      - .env

volumes:
  mysql_data: